### ISSUE TITLE
Issue: Screen slugginesh

### ISSUE THREAD

**Issue by tjsuominen** [ChillLive/ChillLiveWallpaperProject#1]
The latest 0.40 version seemed to bring some unwanted "slugginesh" / slowness when using CLWP. A few examples:

- opening the phone notifications is slower
- using android navigation is sluggish
- when closing apps, there seems to be a couple of seconds slight screen flickering when returning from app x screen > desktop

So in general, when some else UI elements 'covers' the wallpaper, releasing that causes CLWP to regenerate (?) the wall (?) causing this somewhat irritating effect...

It does not matter if you have or have not the scrolling enabled in the advanced settings.

My current phone: OP Nord with Android 12.

This was not the case with the previous 0.3x release.

**Comment by tjsuominen** [comment]
This could be related to the 1st current "Known issue"... sorry if so ;-)

**Comment by ChillLive** [comment]
Hello Tjsuominen, congratulations on finding this page by your own!

When using your launcher on my phone (Niagara), I don't have any new issue compared to the 0.39. The behabior is totally the same...
I will check the new code implented and see if this could be the problem.

EDIT: Ok, I think I identified the flickering problem, working on it. About slowness, I don't know...
I tried to improve the rapidity at which the wallpaper updates when returning to the homescreen. The thing is, this can't be instantaneous. So if your previous time of the day when leaving the homescreen was at daylight, the wallpaper updates with a dark color, you will notice like a flash: the previous frame was day, and the new one is night.
On the nova launcher, the animation when returning to the homescreen is slower than on the Niagara launcher. That's why I never noticed this issue. If you can slow down the animation on the Niagara launcher, it could solve you problem.

**Comment by tjsuominen** [comment]
Yeah, did quick lookup in Github ;) - great project page you have set up!

I'm also running Niagara launcher on my phone as my daily driver.

Let's see if you can isolate and fix the problem (flickering), the slugginesh is then another thing >

The only thing I could think of possibly impacting from my side to it is from Developer options > Window animation scale / Transition animation scale / Animator duration scale for which I have changed the defaults to > .5x (all).

HTH

**Comment by ChillLive** [comment]
Thanks! 

How is the experience so far? Is it better than few days ago? New version is 0.43, let me know if it's a littler better or not

For now its you and me here lol. I didn't share the page yet. I want to solve every issue I can find before continuing to a larger audience.

**Comment by tjsuominen** [comment]
Yes, 0.43 has basically fixed both the flickering and 'unresponsivnes'. Good work!

I would 'invite' others to GitHub too for bughunting :)

Can't wait those upcoming features!
